import Foundation

@main
struct GenerateManifest {
  static func main() throws {
    let arguments = CommandLine.arguments
    guard arguments.count == 3 else {
      fputs("Usage: generate-manifest <input.json> <output.swift>\n", stderr)
      Foundation.exit(1)
    }

    let inputPath = arguments[1]
    let outputPath = arguments[2]

    let inputURL = URL(fileURLWithPath: inputPath)
    let outputURL = URL(fileURLWithPath: outputPath)

    // Read JSON
    let data = try Data(contentsOf: inputURL)
    guard let json = try JSONSerialization
      .jsonObject(with: data) as? [String: Any],
      let databasesArray = json["databases"] as? [[String: Any]]
    else {
      throw NSError(
        domain: "Parse",
        code: 1,
        userInfo: [NSLocalizedDescriptionKey: "Invalid JSON format"],
      )
    }

    // Generate Swift code
    let code = generateSwiftCode(from: databasesArray)
    try code.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  static func generateSwiftCode(from databases: [[String: Any]]) -> String {
    var output = """
    // Generated by GenerateManifestPlugin - DO NOT EDIT
    import Foundation

    extension DatabaseManifest {
      static let generated: DatabaseManifest = {
        let databases: [DatabaseInfo] = [
    """

    for db in databases {
      let language = (db["language"] as? String) ?? ""
      let author = (db["author"] as? String) ?? ""
      let authorName = (db["authorName"] as? String) ?? ""
      let buildTimestamp = (db["buildTimestamp"] as? String) ?? ""
      let gitHash = db["gitHash"] as? String
      let json = db["json"] as? String
      let files = db["files"] as? [String: Any] ?? [:]

      let sutta = (files["sutta"] as? Int) ?? 0
      let vinaya = (files["vinaya"] as? Int) ?? 0
      let abhidhamma = (files["abhidhamma"] as? Int) ?? 0
      let other = (files["other"] as? Int) ?? 0
      let total = (files["total"] as? Int) ?? 0

      output += """

          DatabaseInfo(
            language: \(escape(language)),
            author: \(escape(author)),
            authorName: \(escape(authorName)),
            buildTimestamp: \(escape(buildTimestamp)),
            files: FilesBreakdown(
              sutta: \(sutta),
              vinaya: \(vinaya),
              abhidhamma: \(abhidhamma),
              other: \(other),
              total: \(total)
            ),
            gitHash: \(gitHash.map { escape($0) } ?? "nil"),
            json: \(json.map { escape($0) } ?? "nil")
          ),
      """
    }

    output += """

        ]
        return DatabaseManifest(databases: databases)
      }()
    }
    """

    return output
  }

  static func escape(_ string: String) -> String {
    let escaped = string
      .replacingOccurrences(of: "\\", with: "\\\\")
      .replacingOccurrences(of: "\"", with: "\\\"")
      .replacingOccurrences(of: "\n", with: "\\n")
      .replacingOccurrences(of: "\r", with: "\\r")
      .replacingOccurrences(of: "\t", with: "\\t")
    return "\"\(escaped)\""
  }
}
