//
//  SuttaCentralUid.swift
//  scv-core
//
//  Created by Claude on 2025-12-05.
//  Generated from ../scv-esm/src/uid-expansion.mjs
//

import Foundation

/// UID expansion mapping from collection prefix to abbreviation and name
/// Source: scv-esm/src/uid-expansion.mjs
enum SuttaCentralUid {
  static let abbrMapping: [String: String] = [
    "an": "AN",
    "ap": "Ap",
    "arv": "Arv",
    "avs": "Avs",
    "bv": "Bv",
    "cnd": "Cnd",
    "cp": "Cp",
    "cps": "Cps",
    "da": "DA",
    "kag": "KA",
    "dhp": "Dhp",
    "gdhp": "G-Dhp",
    "g2dhp": "G-2-Dhp",
    "g3dhp": "G-3-Dhp",
    "pdhp": "P-Dhp",
    "divy": "Divy",
    "dk": "Dk",
    "dn": "DN",
    "d": "D",
    "q": "Q",
    "dt": "Dt",
    "dr": "Dr",
    "ds": "Ds",
    "ea": "EA",
    "ea-2": "EA2 [T 150A]",
    "gf": "Gandh",
    "iti": "Iti",
    "isi": "Isibhās",
    "ja": "Ja",
    "jp": "Jp",
    "kam": "Kam",
    "kf": "Khot",
    "kg": "Kg",
    "kn": "KN",
    "kp": "Kp",
    "kv": "Kv",
    "khv": "Khv",
    "lal": "Lal",
    "ma": "MA",
    "mbh": "Mbh",
    "mc": "Mc",
    "mpt": "Mpt",
    "mh": "Mh",
    "mil": "Mil",
    "mn": "MN",
    "mnd": "Mnd",
    "ms": "Ms",
    "mvu": "Mvu",
    "nd": "Nd",
    "ne": "Ne",
    "t1670a": "T 1670 A",
    "t1670b": "T 1670 B",
    "oa": "OA",
    "om": "OM",
    "pe": "Pe",
    "pk": "Pk",
    "pp": "Pp",
    "ps": "Ps",
    "patthana": "Patthana",
    "pf": "Prak",
    "pu": "Pu",
    "praj": "Praj",
    "pv": "Pv",
    "sa": "SA",
    "sa-2": "SA-2",
    "sa-3": "SA-3",
    "sab": "Sab",
    "sag": "Sag",
    "sb": "Sb",
    "sbh": "Sbh",
    "sf": "SF",
    "sg": "Sg",
    "sht": "SHT",
    "sn": "SN",
    "snp": "Snp",
    "spp": "Spp",
    "suy": "Sūy",
    "t": "T",
    "other-t": "Other T",
    "tha-ap": "Tha Ap",
    "thag": "Thag",
    "thi-ap": "Thi Ap",
    "thig": "Thig",
    "tib": "Tib",
    "ud": "Ud",
    "uf": "Uigh",
    "up": "Up",
    "upp": "Upp",
    "utt": "Utt",
    "utg": "Utg",
    "uv": "Uv",
    "uvs": "UvS",
    "ve": "VE",
    "vk": "Vk",
    "vns": "Vns",
    "vs": "VS",
    "vv": "Vv",
    "ya": "Ya",
    "ybs": "Ybs",
    "nidana": "Nidana",
    "pli": "Pli",
    "zh": "Zh",
    "lzh": "Lzh",
    "san": "San",
    "pgd": "Pgd",
    "pra": "Pra",
    "uig": "Uig",
    "xct": "Xct",
    "my": "My",
    "de": "De",
    "en": "En",
    "es": "Es",
    "fr": "Fr",
    "ko": "Ko",
    "ru": "Ru",
    "vi": "Vi",
    "kho": "Kho",
  ]

  static let nameMapping: [String: String] = [
    "an": "Aṅguttara Nikāya",
    "ap": "Āpadāna",
    "arv": "Arthaviniścaya",
    "avs": "Avadānaśataka",
    "bv": "Buddhavaṁsa",
    "cnd": "Cūḷaniddesa",
    "cp": "Cariyāpiṭaka",
    "cps": "Catuṣpariṣatsūtra",
    "da": "Dīrghāgama",
    "kag": "Khuddakāgama",
    "dhp": "Dhammapada",
    "gdhp": "Gāndhārī Dharmapada",
    "g2dhp": "Gāndhārī Dharmapada British Library Fragment 16",
    "g3dhp": "Gāndhārī Dharmapada Split Collection Fragment 3",
    "pdhp": "Prākrit Dharmapada",
    "divy": "Divyāvadāna",
    "dk": "Dharmaskandha",
    "dn": "Dīgha Nikāya",
    "d": "Derge edition",
    "q": "Qianlong (Peking edition of Tibetan canon)",
    "dt": "Dhātukathā",
    "dr": "Dayyaraṭṭhassa Saṅgītitepiṭakaṁ",
    "ds": "Dhammasaṅgaṇī",
    "ea": "Ekottarikāgama (1st)",
    "ea-2": "Ekottarikāgama (2nd)",
    "gf": "Gāndhārī fragments",
    "iti": "Itivuttaka",
    "isi": "Isibhāsiyāiṁ",
    "ja": "Jātaka",
    "jp": "Jnānaprasthāna",
    "kam": "Kammavācā",
    "kf": "Khotanese fragments",
    "kg": "Kangyur",
    "kn": "Khuddaka Nikāya",
    "kp": "Khuddakapāṭha",
    "kv": "Kathāvatthu",
    "khv": "Khuddakavatthu",
    "lal": "Lalitavistara",
    "ma": "Madhyamāgama",
    "mbh": "Mahābhārata",
    "mc": "Mahācūḷātepiṭakaṁ",
    "mpt": "Mahāvyutpatti",
    "mh": "Mahāsūtras",
    "mil": "Milindapañha",
    "mn": "Majjhima Nikāya",
    "mnd": "Mahāniddesa",
    "ms": "Mahasaṅgīti Tipiṭaka",
    "mvu": "Mahāvastu",
    "nd": "Niddesa",
    "ne": "Nettipakaraṇa",
    "t1670a": "Nāgasena Bhikṣu Sūtra (1st)",
    "t1670b": "Nāgasena Bhikṣu Sūtra (2nd)",
    "oa": "Other Āgama Sūtras",
    "om": "Other Mātikā",
    "pe": "Peṭakopadesa",
    "pk": "Prakaraṇapada",
    "pp": "Puggalapaññatti",
    "ps": "Paṭisambhidāmagga",
    "patthana": "Paṭṭhāna",
    "pf": "Prākrit fragments",
    "pu": "Puggalavāda",
    "praj": "Prajnaptiśāstra",
    "pv": "Petavatthu",
    "sa": "Saṁyuktāgama (1st)",
    "sa-2": "Saṁyuktāgama (2nd)",
    "sa-3": "Saṁyuktāgama (3rd)",
    "sab": "Śāriputrābhidharma",
    "sag": "Śarīrārthagāthā",
    "sb": "Saṅghabhedavastu",
    "sbh": "Śrāvakabhūmi",
    "sf": "Sanskrit Āgama Sūtras",
    "sg": "Saṅgītiparyāya",
    "sht": "SHT fragments",
    "sn": "Saṁyutta Nikāya",
    "snp": "Sutta Nipāta",
    "spp": "Śāriputraparipṛcchā",
    "suy": "Sūyagadamgasuttam",
    "t": "Taishō",
    "other-t": "Other Taishō",
    "tha-ap": "Therāpadāna",
    "thag": "Theragāthā",
    "thi-ap": "Therīapadāna",
    "thig": "Therīgāthā",
    "tib": "Tibetan",
    "ud": "Udāna",
    "uf": "Uighur fragments",
    "up": "Upāyikā",
    "upp": "Upaliparipṛcchā",
    "utt": "Uttarādhyayanasūtra",
    "utg": "Uttargantha",
    "uv": "Udānavarga",
    "uvs": "Udānavarga de Subaši",
    "ve": "Vinaya Ekottara",
    "vk": "Vijnānakāya",
    "vns": "Vinayanidānasūtra",
    "vs": "(Vinaya) Saṁyutta",
    "vv": "Vimānavatthu",
    "ya": "Yamaka",
    "ybs": "Yogācārabhūmi",
    "nidana": "Nidāna",
    "pli": "Pāli",
    "zh": "Chinese",
    "lzh": "Literary Chinese",
    "san": "Sanskrit",
    "pgd": "Gāndhārī",
    "pra": "Prākrit",
    "uig": "Uighur",
    "xct": "Classical Tibetan",
    "my": "Burmese",
    "de": "German",
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "ko": "Korean",
    "ru": "Russian",
    "vi": "Vietnamese",
    "kho": "Khotanese",
  ]
}
