//
//  SerializationV1Tests.swift
//  scv-core
//
//  Baseline tests for v1 serialization formats.
//  These tests load actual serialized data from fixture files and ensure that
//  new serialization code can deserialize them without crashing.
//  If these tests fail, it indicates a breaking change in the serialization
//  format that requires migration logic.
//
//  Fixtures are generated by: swift scripts/generate-fixtures.swift
//

import Foundation
@testable import scvCore
import Testing

@Suite("SerializationV1Tests")
struct SerializationV1Tests {
  // MARK: - Constants

  /// V1 serialization baseline version
  static let V1 = "v0.0.222"

  // MARK: - Fixture Loading

  static func loadFixture(_ version: String,
                          _ fileName: String) throws -> Data
  {
    let filename = "\(version)_\(fileName).json"

    // Try Bundle.module first (for packaged tests)
    if let bundle = Bundle.module as Bundle?,
       let url = bundle.url(
         forResource: filename,
         withExtension: nil,
         subdirectory: "Fixtures",
       ),
       let data = try? Data(contentsOf: url)
    {
      return data
    }

    // Fallback to filesystem (for development)
    let fileURL =
      URL(
        fileURLWithPath: "/Users/visakha/dev/scv-app/scv-core/Tests/Fixtures/\(filename)",
      )

    guard FileManager.default.fileExists(atPath: fileURL.path),
          let data = try? Data(contentsOf: fileURL)
    else {
      throw NSError(domain: "FixtureError", code: 1, userInfo: [
        NSLocalizedDescriptionKey: "Could not load fixture: \(filename)",
      ])
    }
    return data
  }

  // MARK: - Card Deserialization Tests

  @Test("Card v1 search card deserializes from fixture")
  func cardV1SearchDeserialization() throws {
    let data = try Self.loadFixture(Self.V1, "Card_Search")
    let decoder = JSONDecoder()
    let card = try decoder.decode(Card.self, from: data)

    #expect(card.cardType == CardType.search)
    #expect(card.typeId == 1)
    #expect(card.searchQuery == "root of suffering")
    #expect(card.suttaReference == "")
    #expect(card.searchResults == nil)
  }

  @Test("Card v1 sutta card deserializes from fixture")
  func cardV1SuttaDeserialization() throws {
    let data = try Self.loadFixture(Self.V1, "Card_Sutta")
    let decoder = JSONDecoder()
    let card = try decoder.decode(Card.self, from: data)

    #expect(card.cardType == CardType.sutta)
    #expect(card.typeId == 2)
    #expect(card.searchQuery == "")
    #expect(card.suttaReference == "sn42.11")
    #expect(card.searchResults == nil)
  }

  @Test("Card v1 with search results deserializes from fixture")
  func cardV1WithSeekerResultsDeserialization() throws {
    let data = try Self.loadFixture(Self.V1, "Card_Search_Results")
    let decoder = JSONDecoder()
    let card = try decoder.decode(Card.self, from: data)

    #expect(card.cardType == CardType.search)
    #expect(card.typeId == 3)
    #expect(card.searchQuery == "root of suffering")
    #expect(card.searchResults != nil)
    #expect(card.searchResults?.author == "sujato")
    #expect(card.searchResults?.suttaRefs.count == 2)
  }

  // MARK: - Settings Deserialization Tests

  @Test("Settings v1 minimal configuration deserializes from fixture")
  func settingsV1MinimalDeserialization() throws {
    let data = try Self.loadFixture(Self.V1, "Settings_Minimal")
    let decoder = JSONDecoder()
    let settings = try decoder.decode(Settings.self, from: data)

    #expect(settings.version == 1)
    #expect(settings.docLang == ScvLanguage.english)
    #expect(settings.refLang == ScvLanguage.english)
    // Fixture contains hardcoded docAuthor - should be preserved exactly
    #expect(settings.docAuthor == "sujato")
    // refAuthor initialized from manifest default for refLang during
    // deserialization
    if let enInfo = DatabaseManifest.shared.defaultAuthorForLanguage("en") {
      #expect(settings.refAuthor == enInfo.author)
    }
    #expect(settings.isDarkModeEnabled == true)
    #expect(settings.maxDoc == 50)
  }

  @Test("Settings v1 with voice configuration deserializes from fixture")
  func settingsV1WithVoiceDeserialization() throws {
    let data = try Self.loadFixture(Self.V1, "Settings_WithVoice")
    let decoder = JSONDecoder()
    let settings = try decoder.decode(Settings.self, from: data)

    #expect(settings.version == 1)
    #expect(settings.docLang == ScvLanguage.english)
    #expect(settings.refLang == ScvLanguage.pli)
    #expect(settings.docAuthor == "soma")
    #expect(settings.refAuthor == "ms")
    #expect(settings.paliSpeech.voiceName == "Daniel")
    #expect(settings.paliSpeech.pitch == 1.1)
    #expect(settings.paliSpeech.rate == 0.95)
    #expect(settings.docSpeech.voiceName == "Samantha")
    #expect(settings.isDarkModeEnabled == false)
    #expect(settings.maxDoc == 100)
  }

  // MARK: - Round-trip Tests

  @Test("Card v1 round-trip serialization from fixture")
  func cardV1RoundTrip() throws {
    // Deserialize from fixture
    let inputData = try Self.loadFixture(Self.V1, "Card_Search")
    let decoder = JSONDecoder()
    let card = try decoder.decode(Card.self, from: inputData)

    // Re-serialize
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    let outputData = try encoder.encode(card)

    // Deserialize again to ensure no data loss
    let card2 = try decoder.decode(Card.self, from: outputData)

    #expect(card.uuid == card2.uuid)
    #expect(card.cardType == card2.cardType)
    #expect(card.searchQuery == card2.searchQuery)

    // Verify searchResultJSON is absent (old cards stay in old format)
    let outputString = String(data: outputData, encoding: .utf8) ?? ""
    #expect(!outputString.contains("searchResultJSON"))
  }

  @Test("Settings v1 round-trip serialization from fixture")
  func settingsV1RoundTrip() throws {
    // Deserialize from fixture
    let inputData = try Self.loadFixture(Self.V1, "Settings_Minimal")
    let decoder = JSONDecoder()
    let settings = try decoder.decode(Settings.self, from: inputData)

    // Re-serialize
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    let outputData = try encoder.encode(settings)

    // Deserialize again
    let settings2 = try decoder.decode(Settings.self, from: outputData)

    #expect(settings.version == settings2.version)
    #expect(settings.docLang == settings2.docLang)
    #expect(settings.docAuthor == settings2.docAuthor)
  }
}
